In [1]:
import requests
import pandas as pd
url = "https://alpha-vantage.p.rapidapi.com/query"
querystring = {"interval": "5min", "function": "TIME_SERIES_INTRADAY", "symbol": "MSFT", "datatype": "json",
               "output_size": "compact"}

headers = {
    "X-RapidAPI-Key": "ff9411e7f8mshc9251362c5e31cap1722bfjsn63362eb4e70d",
    "X-RapidAPI-Host": "alpha-vantage.p.rapidapi.com"
}
response = requests.get(url, headers=headers, params=querystring)
data = response.json()

In [2]:
response.json()

{'Meta Data': {'1. Information': 'Intraday (5min) open, high, low, close prices and volume',
  '2. Symbol': 'MSFT',
  '3. Last Refreshed': '2024-03-05 19:55:00',
  '4. Interval': '5min',
  '5. Output Size': 'Compact',
  '6. Time Zone': 'US/Eastern'},
 'Time Series (5min)': {'2024-03-05 19:55:00': {'1. open': '403.2800',
   '2. high': '403.4900',
   '3. low': '403.0100',
   '4. close': '403.4900',
   '5. volume': '1555'},
  '2024-03-05 19:50:00': {'1. open': '403.3000',
   '2. high': '403.5300',
   '3. low': '403.0000',
   '4. close': '403.2900',
   '5. volume': '4122'},
  '2024-03-05 19:45:00': {'1. open': '403.4800',
   '2. high': '403.7000',
   '3. low': '403.3000',
   '4. close': '403.3000',
   '5. volume': '1880'},
  '2024-03-05 19:40:00': {'1. open': '403.5750',
   '2. high': '403.7500',
   '3. low': '403.3000',
   '4. close': '403.5050',
   '5. volume': '1748'},
  '2024-03-05 19:35:00': {'1. open': '403.5000',
   '2. high': '403.7500',
   '3. low': '403.3000',
   '4. close': '403.5750',
   '5. volume': '1179'},
  '2024-03-05 19:30:00': {'1. open': '403.5250',
   '2. high': '403.7000',
   '3. low': '403.2100',
   '4. close': '403.5000',
   '5. volume': '704'},
  '2024-03-05 19:25:00': {'1. open': '403.5000',
   '2. high': '403.7000',
   '3. low': '403.2200',
   '4. close': '403.3800',
   '5. volume': '1225'},
  '2024-03-05 19:20:00': {'1. open': '403.3950',
   '2. high': '403.7000',
   '3. low': '403.2000',
   '4. close': '403.2000',
   '5. volume': '1753'},
  '2024-03-05 19:15:00': {'1. open': '403.2000',
   '2. high': '403.7400',
   '3. low': '403.2000',
   '4. close': '403.4000',
   '5. volume': '876'},
  '2024-03-05 19:10:00': {'1. open': '403.3000',
   '2. high': '403.7400',
   '3. low': '403.1000',
   '4. close': '403.2100',
   '5. volume': '1649'},
  '2024-03-05 19:05:00': {'1. open': '403.2000',
   '2. high': '403.3000',
   '3. low': '403.1000',
   '4. close': '403.1300',
   '5. volume': '463'},
  '2024-03-05 19:00:00': {'1. open': '403.3300',
   '2. high': '403.5000',
   '3. low': '403.1000',
   '4. close': '403.2000',
   '5. volume': '1142'},
  '2024-03-05 18:55:00': {'1. open': '403.3300',
   '2. high': '403.8800',
   '3. low': '403.2000',
   '4. close': '403.5000',
   '5. volume': '1156'},
  '2024-03-05 18:50:00': {'1. open': '403.3600',
   '2. high': '403.8800',
   '3. low': '403.2500',
   '4. close': '403.6050',
   '5. volume': '691'},
  '2024-03-05 18:45:00': {'1. open': '403.1000',
   '2. high': '403.6900',
   '3. low': '403.1000',
   '4. close': '403.3450',
   '5. volume': '1251'},
  '2024-03-05 18:40:00': {'1. open': '403.5000',
   '2. high': '409.1000',
   '3. low': '403.0200',
   '4. close': '403.3950',
   '5. volume': '4069'},
  '2024-03-05 18:35:00': {'1. open': '403.1000',
   '2. high': '403.9000',
   '3. low': '403.0200',
   '4. close': '403.4300',
   '5. volume': '1809'},
  '2024-03-05 18:30:00': {'1. open': '403.3500',
   '2. high': '403.5000',
   '3. low': '403.0100',
   '4. close': '403.0500',
   '5. volume': '2019'},
  '2024-03-05 18:25:00': {'1. open': '403.5000',
   '2. high': '403.5000',
   '3. low': '403.1100',
   '4. close': '403.3500',
   '5. volume': '1381'},
  '2024-03-05 18:20:00': {'1. open': '403.5000',
   '2. high': '403.5000',
   '3. low': '403.0700',
   '4. close': '403.3500',
   '5. volume': '1307'},
  '2024-03-05 18:15:00': {'1. open': '403.5850',
   '2. high': '403.6700',
   '3. low': '403.1100',
   '4. close': '403.4900',
   '5. volume': '2955'},
  '2024-03-05 18:10:00': {'1. open': '403.7500',
   '2. high': '403.7500',
   '3. low': '403.5000',
   '4. close': '403.5850',
   '5. volume': '1965'},
  '2024-03-05 18:05:00': {'1. open': '403.5500',
   '2. high': '404.2800',
   '3. low': '403.5000',
   '4. close': '403.6300',
   '5. volume': '3387'},
  '2024-03-05 18:00:00': {'1. open': '403.9000',
   '2. high': '404.3600',
   '3. low': '403.5500',
   '4. close': '403.5500',
   '5. volume': '4492'},
  '2024-03-05 17:55:00': {'1. open': '404.0000',
   '2. high': '404.0000',
   '3. low': '403.8300',
   '4. close': '403.9500',
   '5. volume': '296'},
  '2024-03-05 17:50:00': {'1. open': '404.3280',
   '2. high': '404.3500',
   '3. low': '403.9150',
   '4. close': '404.0000',
   '5. volume': '3491'},
  '2024-03-05 17:45:00': {'1. open': '404.3200',
   '2. high': '404.3600',
   '3. low': '404.2000',
   '4. close': '404.3500',
   '5. volume': '1572'},
  '2024-03-05 17:40:00': {'1. open': '404.2200',
   '2. high': '404.3300',
   '3. low': '404.2000',
   '4. close': '404.2700',
   '5. volume': '2045'},
  '2024-03-05 17:35:00': {'1. open': '404.2000',
   '2. high': '404.2500',
   '3. low': '404.0000',
   '4. close': '404.2200',
   '5. volume': '4031'},
  '2024-03-05 17:30:00': {'1. open': '404.1000',
   '2. high': '404.2500',
   '3. low': '404.0230',
   '4. close': '404.1300',
   '5. volume': '4869'},
  '2024-03-05 17:25:00': {'1. open': '404.3000',
   '2. high': '404.3200',
   '3. low': '404.0000',
   '4. close': '404.1000',
   '5. volume': '3781'},
  '2024-03-05 17:20:00': {'1. open': '404.2900',
   '2. high': '404.3500',
   '3. low': '404.2800',
   '4. close': '404.3200',
   '5. volume': '4094'},
  '2024-03-05 17:15:00': {'1. open': '404.2800',
   '2. high': '404.2950',
   '3. low': '404.2300',
   '4. close': '404.2800',
   '5. volume': '981'},
  '2024-03-05 17:10:00': {'1. open': '404.2600',
   '2. high': '404.3400',
   '3. low': '404.2200',
   '4. close': '404.2300',
   '5. volume': '1192'},
  '2024-03-05 17:05:00': {'1. open': '404.2900',
   '2. high': '404.3400',
   '3. low': '402.6500',
   '4. close': '404.3400',
   '5. volume': '30114'},
  '2024-03-05 17:00:00': {'1. open': '404.3100',
   '2. high': '404.3500',
   '3. low': '404.2200',
   '4. close': '404.2800',
   '5. volume': '2301'},
  '2024-03-05 16:55:00': {'1. open': '404.1800',
   '2. high': '422.1450',
   '3. low': '337.1600',
   '4. close': '404.3000',
   '5. volume': '3651'},
  '2024-03-05 16:50:00': {'1. open': '404.1200',
   '2. high': '412.7650',
   '3. low': '347.4260',
   '4. close': '404.1800',
   '5. volume': '6444'},
  '2024-03-05 16:45:00': {'1. open': '404.0400',
   '2. high': '404.1900',
   '3. low': '404.0300',
   '4. close': '404.1400',
   '5. volume': '3405'},
  '2024-03-05 16:40:00': {'1. open': '404.1800',
   '2. high': '404.2000',
   '3. low': '402.6500',
   '4. close': '404.0250',
   '5. volume': '4713'},
  '2024-03-05 16:35:00': {'1. open': '404.1300',
   '2. high': '404.1800',
   '3. low': '403.9200',
   '4. close': '404.1600',
   '5. volume': '6448'},
  '2024-03-05 16:30:00': {'1. open': '403.5500',
   '2. high': '404.1500',
   '3. low': '403.5250',
   '4. close': '404.1300',
   '5. volume': '13987'},
  '2024-03-05 16:25:00': {'1. open': '403.7200',
   '2. high': '403.7200',
   '3. low': '403.5000',
   '4. close': '403.5500',
   '5. volume': '5040'},
  '2024-03-05 16:20:00': {'1. open': '403.8700',
   '2. high': '403.9900',
   '3. low': '401.4000',
   '4. close': '403.7000',
   '5. volume': '120917'},
  '2024-03-05 16:15:00': {'1. open': '403.8700',
   '2. high': '406.0850',
   '3. low': '401.9380',
   '4. close': '403.8100',
   '5. volume': '19110'},
  '2024-03-05 16:10:00': {'1. open': '403.6200',
   '2. high': '404.0000',
   '3. low': '402.6500',
   '4. close': '403.9200',
   '5. volume': '15320'},
  '2024-03-05 16:05:00': {'1. open': '402.8500',
   '2. high': '416.5050',
   '3. low': '402.6500',
   '4. close': '403.5900',
   '5. volume': '200320'},
  '2024-03-05 16:00:00': {'1. open': '402.8500',
   '2. high': '403.8860',
   '3. low': '402.4580',
   '4. close': '402.8500',
   '5. volume': '9198700'},
  '2024-03-05 15:55:00': {'1. open': '402.0600',
   '2. high': '402.8500',
   '3. low': '401.9400',
   '4. close': '402.8500',
   '5. volume': '1098216'},
  '2024-03-05 15:50:00': {'1. open': '402.2800',
   '2. high': '402.4800',
   '3. low': '401.3800',
   '4. close': '402.1050',
   '5. volume': '650669'},
  '2024-03-05 15:45:00': {'1. open': '401.8700',
   '2. high': '402.3600',
   '3. low': '401.7600',
   '4. close': '402.2900',
   '5. volume': '334368'},
  '2024-03-05 15:40:00': {'1. open': '401.5000',
   '2. high': '401.9200',
   '3. low': '401.1400',
   '4. close': '401.8400',
   '5. volume': '374089'},
  '2024-03-05 15:35:00': {'1. open': '401.5200',
   '2. high': '401.6900',
   '3. low': '401.2200',
   '4. close': '401.4950',
   '5. volume': '230445'},
  '2024-03-05 15:30:00': {'1. open': '400.7800',
   '2. high': '401.6000',
   '3. low': '400.7400',
   '4. close': '401.5250',
   '5. volume': '387552'},
  '2024-03-05 15:25:00': {'1. open': '400.9600',
   '2. high': '401.1200',
   '3. low': '400.6740',
   '4. close': '400.7700',
   '5. volume': '247069'},
  '2024-03-05 15:20:00': {'1. open': '400.8550',
   '2. high': '401.0400',
   '3. low': '400.6400',
   '4. close': '401.0000',
   '5. volume': '286171'},
  '2024-03-05 15:15:00': {'1. open': '401.0000',
   '2. high': '401.2900',
   '3. low': '400.8400',
   '4. close': '400.8500',
   '5. volume': '220832'},
  '2024-03-05 15:10:00': {'1. open': '401.3950',
   '2. high': '401.5600',
   '3. low': '400.9900',
   '4. close': '401.0000',
   '5. volume': '226399'},
  '2024-03-05 15:05:00': {'1. open': '402.0250',
   '2. high': '402.2600',
   '3. low': '401.1850',
   '4. close': '401.3950',
   '5. volume': '227612'},
  '2024-03-05 15:00:00': {'1. open': '401.3200',
   '2. high': '402.0500',
   '3. low': '401.3200',
   '4. close': '402.0100',
   '5. volume': '235127'},
  '2024-03-05 14:55:00': {'1. open': '401.1600',
   '2. high': '401.4300',
   '3. low': '401.1300',
   '4. close': '401.3100',
   '5. volume': '166267'},
  '2024-03-05 14:50:00': {'1. open': '400.8000',
   '2. high': '401.2880',
   '3. low': '400.7850',
   '4. close': '401.1470',
   '5. volume': '144283'},
  '2024-03-05 14:45:00': {'1. open': '401.0300',
   '2. high': '401.0900',
   '3. low': '400.6600',
   '4. close': '400.7850',
   '5. volume': '315779'},
  '2024-03-05 14:40:00': {'1. open': '401.5400',
   '2. high': '401.6600',
   '3. low': '401.0200',
   '4. close': '401.0500',
   '5. volume': '162270'},
  '2024-03-05 14:35:00': {'1. open': '401.6000',
   '2. high': '401.7900',
   '3. low': '401.2600',
   '4. close': '401.5500',
   '5. volume': '140860'},
  '2024-03-05 14:30:00': {'1. open': '402.1000',
   '2. high': '402.1750',
   '3. low': '401.4870',
   '4. close': '401.5900',
   '5. volume': '152526'},
  '2024-03-05 14:25:00': {'1. open': '402.0870',
   '2. high': '402.4100',
   '3. low': '401.9520',
   '4. close': '402.0950',
   '5. volume': '137449'},
  '2024-03-05 14:20:00': {'1. open': '401.9650',
   '2. high': '402.1900',
   '3. low': '401.7500',
   '4. close': '402.0900',
   '5. volume': '143454'},
  '2024-03-05 14:15:00': {'1. open': '402.0500',
   '2. high': '402.5000',
   '3. low': '401.8400',
   '4. close': '401.9700',
   '5. volume': '156176'},
  '2024-03-05 14:10:00': {'1. open': '402.3200',
   '2. high': '402.5900',
   '3. low': '402.0200',
   '4. close': '402.0400',
   '5. volume': '161217'},
  '2024-03-05 14:05:00': {'1. open': '401.7500',
   '2. high': '402.4200',
   '3. low': '401.5600',
   '4. close': '402.2920',
   '5. volume': '168008'},
  '2024-03-05 14:00:00': {'1. open': '401.5300',
   '2. high': '401.8400',
   '3. low': '401.3000',
   '4. close': '401.7600',
   '5. volume': '121877'},
  '2024-03-05 13:55:00': {'1. open': '401.6300',
   '2. high': '401.8800',
   '3. low': '401.4500',
   '4. close': '401.5300',
   '5. volume': '148685'},
  '2024-03-05 13:50:00': {'1. open': '401.6200',
   '2. high': '401.8100',
   '3. low': '401.3100',
   '4. close': '401.6450',
   '5. volume': '180297'},
  '2024-03-05 13:45:00': {'1. open': '401.3200',
   '2. high': '401.7300',
   '3. low': '401.2600',
   '4. close': '401.6300',
   '5. volume': '159520'},
  '2024-03-05 13:40:00': {'1. open': '402.1700',
   '2. high': '402.2200',
   '3. low': '401.2490',
   '4. close': '401.2900',
   '5. volume': '317881'},
  '2024-03-05 13:35:00': {'1. open': '402.6800',
   '2. high': '402.8200',
   '3. low': '402.1400',
   '4. close': '402.1600',
   '5. volume': '176524'},
  '2024-03-05 13:30:00': {'1. open': '402.5700',
   '2. high': '402.8500',
   '3. low': '402.4300',
   '4. close': '402.6600',
   '5. volume': '140049'},
  '2024-03-05 13:25:00': {'1. open': '402.2200',
   '2. high': '402.6900',
   '3. low': '402.2200',
   '4. close': '402.5900',
   '5. volume': '135642'},
  '2024-03-05 13:20:00': {'1. open': '402.4750',
   '2. high': '402.5890',
   '3. low': '402.1400',
   '4. close': '402.2500',
   '5. volume': '141009'},
  '2024-03-05 13:15:00': {'1. open': '402.9350',
   '2. high': '402.9800',
   '3. low': '402.3600',
   '4. close': '402.4700',
   '5. volume': '168802'},
  '2024-03-05 13:10:00': {'1. open': '403.0000',
   '2. high': '403.2600',
   '3. low': '402.8500',
   '4. close': '402.9500',
   '5. volume': '109704'},
  '2024-03-05 13:05:00': {'1. open': '403.1300',
   '2. high': '403.1400',
   '3. low': '402.7500',
   '4. close': '402.9870',
   '5. volume': '126538'},
  '2024-03-05 13:00:00': {'1. open': '403.3800',
   '2. high': '403.4700',
   '3. low': '402.9610',
   '4. close': '403.1200',
   '5. volume': '146230'},
  '2024-03-05 12:55:00': {'1. open': '403.7500',
   '2. high': '403.9800',
   '3. low': '403.3600',
   '4. close': '403.3700',
   '5. volume': '118885'},
  '2024-03-05 12:50:00': {'1. open': '403.7600',
   '2. high': '403.8900',
   '3. low': '403.5800',
   '4. close': '403.7400',
   '5. volume': '81857'},
  '2024-03-05 12:45:00': {'1. open': '403.9200',
   '2. high': '404.2130',
   '3. low': '403.7500',
   '4. close': '403.7510',
   '5. volume': '92855'},
  '2024-03-05 12:40:00': {'1. open': '403.8300',
   '2. high': '403.9800',
   '3. low': '403.5600',
   '4. close': '403.9350',
   '5. volume': '129892'},
  '2024-03-05 12:35:00': {'1. open': '404.0300',
   '2. high': '404.0500',
   '3. low': '403.7300',
   '4. close': '403.8230',
   '5. volume': '126556'},
  '2024-03-05 12:30:00': {'1. open': '404.4400',
   '2. high': '404.5700',
   '3. low': '403.9900',
   '4. close': '404.0100',
   '5. volume': '101513'},
  '2024-03-05 12:25:00': {'1. open': '404.3600',
   '2. high': '404.7100',
   '3. low': '404.3300',
   '4. close': '404.4150',
   '5. volume': '152847'},
  '2024-03-05 12:20:00': {'1. open': '404.2500',
   '2. high': '404.5000',
   '3. low': '404.0400',
   '4. close': '404.3700',
   '5. volume': '117339'},
  '2024-03-05 12:15:00': {'1. open': '404.3500',
   '2. high': '404.3780',
   '3. low': '404.1300',
   '4. close': '404.2800',
   '5. volume': '88209'},
  '2024-03-05 12:10:00': {'1. open': '404.4100',
   '2. high': '404.4900',
   '3. low': '404.0000',
   '4. close': '404.3200',
   '5. volume': '121679'},
  '2024-03-05 12:05:00': {'1. open': '404.2000',
   '2. high': '404.4370',
   '3. low': '404.0700',
   '4. close': '404.4100',
   '5. volume': '117196'},
  '2024-03-05 12:00:00': {'1. open': '404.1800',
   '2. high': '404.3700',
   '3. low': '403.9800',
   '4. close': '404.2090',
   '5. volume': '140361'},
  '2024-03-05 11:55:00': {'1. open': '403.4400',
   '2. high': '404.1800',
   '3. low': '403.2800',
   '4. close': '404.1400',
   '5. volume': '178208'},
  '2024-03-05 11:50:00': {'1. open': '403.4000',
   '2. high': '403.5100',
   '3. low': '403.2500',
   '4. close': '403.4500',
   '5. volume': '118766'},
  '2024-03-05 11:45:00': {'1. open': '403.4500',
   '2. high': '403.6100',
   '3. low': '403.0000',
   '4. close': '403.3900',
   '5. volume': '152705'},
  '2024-03-05 11:40:00': {'1. open': '403.4800',
   '2. high': '403.8200',
   '3. low': '402.9200',
   '4. close': '403.4750',
   '5. volume': '248425'}}}

In [3]:
meta_data = data['Meta Data']
time_series = data['Time Series (5min)']

timestamps = pd.to_datetime(list(time_series.keys()))
df = pd.DataFrame(time_series.values(), index=timestamps)

# Reset the index to get timestamp as a column
df = df.reset_index()

# Rename the timestamp column
df = df.rename(columns={"index": 'timestamp'})

# Break timestamp into subcolumns
df['year'] = df['timestamp'].dt.year
df['month'] = df['timestamp'].dt.month
df['day'] = df['timestamp'].dt.day
df['hour'] = df['timestamp'].dt.hour
df['minute'] = df['timestamp'].dt.minute

In [4]:
df

,timestamp,1. open,2. high,3. low,4. close,5. volume,year,month,day,hour,minute
0,2024-03-05 19:55:00,403.2800,403.4900,403.0100,403.4900,1555,2024,3,5,19,55
1,2024-03-05 19:50:00,403.3000,403.5300,403.0000,403.2900,4122,2024,3,5,19,50
2,2024-03-05 19:45:00,403.4800,403.7000,403.3000,403.3000,1880,2024,3,5,19,45
3,2024-03-05 19:40:00,403.5750,403.7500,403.3000,403.5050,1748,2024,3,5,19,40
4,2024-03-05 19:35:00,403.5000,403.7500,403.3000,403.5750,1179,2024,3,5,19,35
...,...,...,...,...,...,...,...,...,...,...,...
95,2024-03-05 12:00:00,404.1800,404.3700,403.9800,404.2090,140361,2024,3,5,12,0
96,2024-03-05 11:55:00,403.4400,404.1800,403.2800,404.1400,178208,2024,3,5,11,55
97,2024-03-05 11:50:00,403.4000,403.5100,403.2500,403.4500,118766,2024,3,5,11,50
98,2024-03-05 11:45:00,403.4500,403.6100,403.0000,403.3900,152705,2024,3,5,11,45
99,2024-03-05 11:40:00,403.4800,403.8200,402.9200,403.4750,248425,2024,3,5,11,40

In [5]:
df.isna().sum()

timestamp    0
1. open      0
2. high      0
3. low       0
4. close     0
5. volume    0
year         0
month        0
day          0
hour         0
minute       0
dtype: int64

In [6]:
df = df.drop('timestamp',axis=1)

In [7]:
df

,1. open,2. high,3. low,4. close,5. volume,year,month,day,hour,minute
0,403.2800,403.4900,403.0100,403.4900,1555,2024,3,5,19,55
1,403.3000,403.5300,403.0000,403.2900,4122,2024,3,5,19,50
2,403.4800,403.7000,403.3000,403.3000,1880,2024,3,5,19,45
3,403.5750,403.7500,403.3000,403.5050,1748,2024,3,5,19,40
4,403.5000,403.7500,403.3000,403.5750,1179,2024,3,5,19,35
...,...,...,...,...,...,...,...,...,...,...
95,404.1800,404.3700,403.9800,404.2090,140361,2024,3,5,12,0
96,403.4400,404.1800,403.2800,404.1400,178208,2024,3,5,11,55
97,403.4000,403.5100,403.2500,403.4500,118766,2024,3,5,11,50
98,403.4500,403.6100,403.0000,403.3900,152705,2024,3,5,11,45
99,403.4800,403.8200,402.9200,403.4750,248425,2024,3,5,11,40

In [9]:
!pip install -U ydata-profiling[notebook]==4.0.0 matplotlib==3.5.1

Collecting ydata-profiling[notebook]==4.0.0
  Downloading ydata_profiling-4.0.0-py2.py3-none-any.whl (344 kB)
     -------------------------------------- 344.5/344.5 kB 2.7 MB/s eta 0:00:00
Collecting matplotlib==3.5.1
  Downloading matplotlib-3.5.1-cp39-cp39-win_amd64.whl (7.2 MB)
     ---------------------------------------- 7.2/7.2 MB 3.3 MB/s eta 0:00:00
Requirement already satisfied: pandas!=1.4.0,<1.6,>1.1 in c:\users\driti singhania\anaconda3\lib\site-packages (from ydata-profiling[notebook]==4.0.0) (1.4.4)
Collecting visions[type_image_path]==0.7.5
  Using cached visions-0.7.5-py3-none-any.whl (102 kB)
Collecting multimethod<1.10,>=1.4
  Downloading multimethod-1.9.1-py3-none-any.whl (10 kB)
Collecting phik<0.13,>=0.11.1
  Using cached phik-0.12.4-cp39-cp39-win_amd64.whl (666 kB)
Requirement already satisfied: statsmodels<0.14,>=0.13.2 in c:\users\driti singhania\anaconda3\lib\site-packages (from ydata-profiling[notebook]==4.0.0) (0.13.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in c:\users\driti singhania\anaconda3\lib\site-packages (from ydata-profiling[notebook]==4.0.0) (2.11.3)
Collecting pydantic<1.11,>=1.8.1
  Downloading pydantic-1.10.14-cp39-cp39-win_amd64.whl (2.2 MB)
     ---------------------------------------- 2.2/2.2 MB 3.4 MB/s eta 0:00:00
Collecting numpy<1.24,>=1.16.0
  Downloading numpy-1.23.5-cp39-cp39-win_amd64.whl (14.7 MB)
     ---------------------------------------- 14.7/14.7 MB 2.0 MB/s eta 0:00:00
Requirement already satisfied: requests<2.29,>=2.24.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from ydata-profiling[notebook]==4.0.0) (2.28.1)
Requirement already satisfied: seaborn<0.13,>=0.10.1 in c:\users\driti singhania\anaconda3\lib\site-packages (from ydata-profiling[notebook]==4.0.0) (0.11.2)
Requirement already satisfied: tqdm<4.65,>=4.48.2 in c:\users\driti singhania\anaconda3\lib\site-packages (from ydata-profiling[notebook]==4.0.0) (4.64.1)
Requirement already satisfied: scipy<1.10,>=1.4.1 in c:\users\driti singhania\anaconda3\lib\site-packages (from ydata-profiling[notebook]==4.0.0) (1.9.1)
Collecting typeguard<2.14,>=2.13.2
  Downloading typeguard-2.13.3-py3-none-any.whl (17 kB)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from ydata-profiling[notebook]==4.0.0) (6.0)
Requirement already satisfied: htmlmin==0.1.12 in c:\users\driti singhania\anaconda3\lib\site-packages (from ydata-profiling[notebook]==4.0.0) (0.1.12)
Requirement already satisfied: ipywidgets>=7.5.1 in c:\users\driti singhania\anaconda3\lib\site-packages (from ydata-profiling[notebook]==4.0.0) (7.6.5)
Requirement already satisfied: jupyter-client>=5.3.4 in c:\users\driti singhania\anaconda3\lib\site-packages (from ydata-profiling[notebook]==4.0.0) (7.3.4)
Requirement already satisfied: jupyter-core>=4.6.3 in c:\users\driti singhania\anaconda3\lib\site-packages (from ydata-profiling[notebook]==4.0.0) (4.11.1)
Requirement already satisfied: cycler>=0.10 in c:\users\driti singhania\anaconda3\lib\site-packages (from matplotlib==3.5.1) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\driti singhania\anaconda3\lib\site-packages (from matplotlib==3.5.1) (1.4.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\driti singhania\anaconda3\lib\site-packages (from matplotlib==3.5.1) (3.0.9)
Requirement already satisfied: pillow>=6.2.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from matplotlib==3.5.1) (9.2.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from matplotlib==3.5.1) (4.25.0)
Requirement already satisfied: packaging>=20.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from matplotlib==3.5.1) (21.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\driti singhania\anaconda3\lib\site-packages (from matplotlib==3.5.1) (2.8.2)
Requirement already satisfied: attrs>=19.3.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.5->ydata-profiling[notebook]==4.0.0) (21.4.0)
Requirement already satisfied: tangled-up-in-unicode>=0.0.4 in c:\users\driti singhania\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.5->ydata-profiling[notebook]==4.0.0) (0.2.0)
Requirement already satisfied: networkx>=2.4 in c:\users\driti singhania\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.5->ydata-profiling[notebook]==4.0.0) (2.8.4)
Collecting imagehash
  Using cached ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
Requirement already satisfied: ipython-genutils~=0.2.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (0.2.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\driti singhania\anaconda3\lib\site-packages (from ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (5.1.1)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (1.0.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (3.5.2)
Requirement already satisfied: ipython>=4.0.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (7.31.1)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (5.5.0)
Requirement already satisfied: ipykernel>=4.5.1 in c:\users\driti singhania\anaconda3\lib\site-packages (from ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (6.15.2)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\driti singhania\anaconda3\lib\site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling[notebook]==4.0.0) (2.0.1)
Requirement already satisfied: pyzmq>=23.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from jupyter-client>=5.3.4->ydata-profiling[notebook]==4.0.0) (23.2.0)
Requirement already satisfied: tornado>=6.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from jupyter-client>=5.3.4->ydata-profiling[notebook]==4.0.0) (6.1)
Requirement already satisfied: nest-asyncio>=1.5.4 in c:\users\driti singhania\anaconda3\lib\site-packages (from jupyter-client>=5.3.4->ydata-profiling[notebook]==4.0.0) (1.5.5)
Requirement already satisfied: entrypoints in c:\users\driti singhania\anaconda3\lib\site-packages (from jupyter-client>=5.3.4->ydata-profiling[notebook]==4.0.0) (0.4)
Requirement already satisfied: pywin32>=1.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from jupyter-core>=4.6.3->ydata-profiling[notebook]==4.0.0) (302)
Requirement already satisfied: pytz>=2020.1 in c:\users\driti singhania\anaconda3\lib\site-packages (from pandas!=1.4.0,<1.6,>1.1->ydata-profiling[notebook]==4.0.0) (2022.1)
Requirement already satisfied: joblib>=0.14.1 in c:\users\driti singhania\anaconda3\lib\site-packages (from phik<0.13,>=0.11.1->ydata-profiling[notebook]==4.0.0) (1.1.0)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from pydantic<1.11,>=1.8.1->ydata-profiling[notebook]==4.0.0) (4.8.0)
Requirement already satisfied: six>=1.5 in c:\users\driti singhania\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib==3.5.1) (1.16.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\driti singhania\anaconda3\lib\site-packages (from requests<2.29,>=2.24.0->ydata-profiling[notebook]==4.0.0) (2022.9.14)
Requirement already satisfied: idna<4,>=2.5 in c:\users\driti singhania\anaconda3\lib\site-packages (from requests<2.29,>=2.24.0->ydata-profiling[notebook]==4.0.0) (3.3)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\driti singhania\anaconda3\lib\site-packages (from requests<2.29,>=2.24.0->ydata-profiling[notebook]==4.0.0) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\driti singhania\anaconda3\lib\site-packages (from requests<2.29,>=2.24.0->ydata-profiling[notebook]==4.0.0) (1.26.11)
Requirement already satisfied: patsy>=0.5.2 in c:\users\driti singhania\anaconda3\lib\site-packages (from statsmodels<0.14,>=0.13.2->ydata-profiling[notebook]==4.0.0) (0.5.2)
Requirement already satisfied: colorama in c:\users\driti singhania\anaconda3\lib\site-packages (from tqdm<4.65,>=4.48.2->ydata-profiling[notebook]==4.0.0) (0.4.5)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\driti singhania\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (0.1.6)
Requirement already satisfied: psutil in c:\users\driti singhania\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (5.9.0)
Requirement already satisfied: debugpy>=1.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (1.5.1)
Requirement already satisfied: pickleshare in c:\users\driti singhania\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (0.7.5)
Requirement already satisfied: backcall in c:\users\driti singhania\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (0.2.0)
Requirement already satisfied: setuptools>=18.5 in c:\users\driti singhania\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (63.4.1)
Requirement already satisfied: pygments in c:\users\driti singhania\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (2.11.2)
Requirement already satisfied: decorator in c:\users\driti singhania\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (5.1.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (3.0.20)
Requirement already satisfied: jedi>=0.16 in c:\users\driti singhania\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (0.18.1)
Requirement already satisfied: fastjsonschema in c:\users\driti singhania\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\driti singhania\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (4.16.0)
Requirement already satisfied: notebook>=4.4.1 in c:\users\driti singhania\anaconda3\lib\site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (6.4.12)
Requirement already satisfied: PyWavelets in c:\users\driti singhania\anaconda3\lib\site-packages (from imagehash->visions[type_image_path]==0.7.5->ydata-profiling[notebook]==4.0.0) (1.3.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (0.8.3)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (0.18.0)
Requirement already satisfied: argon2-cffi in c:\users\driti singhania\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (21.3.0)
Requirement already satisfied: nbconvert>=5 in c:\users\driti singhania\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (6.4.4)
Requirement already satisfied: Send2Trash>=1.8.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (1.8.0)
Requirement already satisfied: prometheus-client in c:\users\driti singhania\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (0.14.1)
Requirement already satisfied: terminado>=0.8.3 in c:\users\driti singhania\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (0.13.1)
Requirement already satisfied: wcwidth in c:\users\driti singhania\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (0.2.5)
Requirement already satisfied: testpath in c:\users\driti singhania\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (0.6.0)
Requirement already satisfied: jupyterlab-pygments in c:\users\driti singhania\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (0.1.2)
Requirement already satisfied: bleach in c:\users\driti singhania\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (4.1.0)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\driti singhania\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (0.8.4)
Requirement already satisfied: beautifulsoup4 in c:\users\driti singhania\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (4.11.1)
Requirement already satisfied: defusedxml in c:\users\driti singhania\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (0.7.1)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\driti singhania\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (1.5.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (0.5.13)
Requirement already satisfied: pywinpty>=1.1.0 in c:\users\driti singhania\anaconda3\lib\site-packages (from terminado>=0.8.3->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (2.0.2)
Requirement already satisfied: argon2-cffi-bindings in c:\users\driti singhania\anaconda3\lib\site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (21.2.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\driti singhania\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (1.15.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\driti singhania\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (2.3.1)
Requirement already satisfied: webencodings in c:\users\driti singhania\anaconda3\lib\site-packages (from bleach->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (0.5.1)
Requirement already satisfied: pycparser in c:\users\driti singhania\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->ydata-profiling[notebook]==4.0.0) (2.21)
Installing collected packages: typeguard, pydantic, numpy, multimethod, matplotlib, visions, phik, imagehash, ydata-profiling
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.4
    Uninstalling numpy-1.24.4:
      Successfully uninstalled numpy-1.24.4

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\DRITI SINGHANIA\\anaconda3\\Lib\\site-packages\\~umpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll'
Consider using the `--user` option or check the permissions.

In [19]:
import pandas as pd
from ydata_profiling import ProfileReport

profile = ProfileReport(df, title='Pandas Profiling Report', explorative=True)
profile.to_file("output.html")

ModuleNotFoundError: No module named 'ydata_profiling'