In [1]:
import pandas as pd
df = pd.read_csv('Student Engagement Level-Binary.csv')
df

,Student ID,# Logins,# Content Reads,# Forum Reads,# Forum Posts,# Quiz Reviews before submission,Assignment 1 lateness indicator,Assignment 2 lateness indicator,Assignment 3 lateness indicator,Assignment 1 duration to submit (in hours),Assignment 2 duration to submit (in hours),Assignment 3 duration to submit (in hours),Average time to submit assignment (in hours),Engagement Level
0,student000000,143,344,58,0,3,0,0,0,178.166667,92.716667,116.166667,129.016667,H
1,student000001,70,342,0,0,4,0,0,0,294.033333,196.083333,217.750000,235.955556,L
2,student000002,42,219,0,0,3,0,0,0,169.600000,235.733333,260.333333,221.888889,L
3,student000003,92,271,2,0,6,0,0,0,341.150000,245.900000,271.216667,286.088889,L
4,student000004,116,379,0,0,1,0,0,0,325.500000,236.283333,260.733333,274.172222,L
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,student000481,98,281,0,0,1,0,0,0,175.200000,89.966667,109.266667,124.811111,H
482,student000482,85,258,1,0,2,0,0,0,127.633333,58.783333,80.550000,88.988889,H
483,student000483,99,206,0,0,6,0,0,0,177.850000,185.400000,220.216667,194.488889,L
484,student000484,51,158,0,0,2,0,0,0,125.900000,32.450000,44.466667,67.605556,H
485,student000485,89,289,0,0,0,0,0,0,313.183333,214.766667,235.366667,254.438889,L

In [3]:
df = df.drop('Student ID',axis=1)

In [4]:
df

,# Logins,# Content Reads,# Forum Reads,# Forum Posts,# Quiz Reviews before submission,Assignment 1 lateness indicator,Assignment 2 lateness indicator,Assignment 3 lateness indicator,Assignment 1 duration to submit (in hours),Assignment 2 duration to submit (in hours),Assignment 3 duration to submit (in hours),Average time to submit assignment (in hours),Engagement Level
0,143,344,58,0,3,0,0,0,178.166667,92.716667,116.166667,129.016667,H
1,70,342,0,0,4,0,0,0,294.033333,196.083333,217.750000,235.955556,L
2,42,219,0,0,3,0,0,0,169.600000,235.733333,260.333333,221.888889,L
3,92,271,2,0,6,0,0,0,341.150000,245.900000,271.216667,286.088889,L
4,116,379,0,0,1,0,0,0,325.500000,236.283333,260.733333,274.172222,L
...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,98,281,0,0,1,0,0,0,175.200000,89.966667,109.266667,124.811111,H
482,85,258,1,0,2,0,0,0,127.633333,58.783333,80.550000,88.988889,H
483,99,206,0,0,6,0,0,0,177.850000,185.400000,220.216667,194.488889,L
484,51,158,0,0,2,0,0,0,125.900000,32.450000,44.466667,67.605556,H
485,89,289,0,0,0,0,0,0,313.183333,214.766667,235.366667,254.438889,L

In [5]:
df.isna().mean()*100

# Logins                                        0.0
# Content Reads                                 0.0
# Forum Reads                                   0.0
# Forum Posts                                   0.0
# Quiz Reviews before submission                0.0
Assignment 1 lateness indicator                 0.0
Assignment 2 lateness indicator                 0.0
Assignment 3 lateness indicator                 0.0
Assignment 1 duration to submit (in hours)      0.0
Assignment 2 duration to submit (in hours)      0.0
Assignment 3 duration to submit (in hours)      0.0
Average time to submit assignment (in hours)    0.0
Engagement Level                                0.0
dtype: float64

In [6]:
# We use label encoding as we need to encode target variable
 
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 


df['Engagement Level']= label_encoder.fit_transform(df['Engagement Level']) 

df['Engagement Level'].unique()

array([0, 1])

In [7]:
df

,# Logins,# Content Reads,# Forum Reads,# Forum Posts,# Quiz Reviews before submission,Assignment 1 lateness indicator,Assignment 2 lateness indicator,Assignment 3 lateness indicator,Assignment 1 duration to submit (in hours),Assignment 2 duration to submit (in hours),Assignment 3 duration to submit (in hours),Average time to submit assignment (in hours),Engagement Level
0,143,344,58,0,3,0,0,0,178.166667,92.716667,116.166667,129.016667,0
1,70,342,0,0,4,0,0,0,294.033333,196.083333,217.750000,235.955556,1
2,42,219,0,0,3,0,0,0,169.600000,235.733333,260.333333,221.888889,1
3,92,271,2,0,6,0,0,0,341.150000,245.900000,271.216667,286.088889,1
4,116,379,0,0,1,0,0,0,325.500000,236.283333,260.733333,274.172222,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,98,281,0,0,1,0,0,0,175.200000,89.966667,109.266667,124.811111,0
482,85,258,1,0,2,0,0,0,127.633333,58.783333,80.550000,88.988889,0
483,99,206,0,0,6,0,0,0,177.850000,185.400000,220.216667,194.488889,1
484,51,158,0,0,2,0,0,0,125.900000,32.450000,44.466667,67.605556,0
485,89,289,0,0,0,0,0,0,313.183333,214.766667,235.366667,254.438889,1

In [11]:
for column_name in df.columns:
    column = df[column_name]
    # Get the count of Zeros in column 
    count = (column == 0).sum()
    print(count)

1
0
398
450
99
474
474
479
0
0
0
0
259

In [13]:
# There are many columns which have a lot of zero values. So we will use Max Absolute Normalization.
columns = ['# Forum Reads','# Forum Posts','# Quiz Reviews before submission','Assignment 1 lateness indicator','Assignment 2 lateness indicator','Assignment 3 lateness indicator']
for i in columns:
    df[i] = df[i] / df[i].abs().max()
df

,# Logins,# Content Reads,# Forum Reads,# Forum Posts,# Quiz Reviews before submission,Assignment 1 lateness indicator,Assignment 2 lateness indicator,Assignment 3 lateness indicator,Assignment 1 duration to submit (in hours),Assignment 2 duration to submit (in hours),Assignment 3 duration to submit (in hours),Average time to submit assignment (in hours),Engagement Level
0,143,344,1.000000,0.0,0.250000,0.0,0.0,0.0,178.166667,92.716667,116.166667,129.016667,0
1,70,342,0.000000,0.0,0.333333,0.0,0.0,0.0,294.033333,196.083333,217.750000,235.955556,1
2,42,219,0.000000,0.0,0.250000,0.0,0.0,0.0,169.600000,235.733333,260.333333,221.888889,1
3,92,271,0.034483,0.0,0.500000,0.0,0.0,0.0,341.150000,245.900000,271.216667,286.088889,1
4,116,379,0.000000,0.0,0.083333,0.0,0.0,0.0,325.500000,236.283333,260.733333,274.172222,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,98,281,0.000000,0.0,0.083333,0.0,0.0,0.0,175.200000,89.966667,109.266667,124.811111,0
482,85,258,0.017241,0.0,0.166667,0.0,0.0,0.0,127.633333,58.783333,80.550000,88.988889,0
483,99,206,0.000000,0.0,0.500000,0.0,0.0,0.0,177.850000,185.400000,220.216667,194.488889,1
484,51,158,0.000000,0.0,0.166667,0.0,0.0,0.0,125.900000,32.450000,44.466667,67.605556,0
485,89,289,0.000000,0.0,0.000000,0.0,0.0,0.0,313.183333,214.766667,235.366667,254.438889,1

In [14]:
columns = ['# Logins','# Content Reads','Assignment 1 duration to submit (in hours)','Assignment 2 duration to submit (in hours)','Assignment 3 duration to submit (in hours)','Average time to submit assignment (in hours)']
for i in columns:
    mean = df[i].mean()
    max = df[i].max()
    min = df[i].min()
    df[i] = (df[i] - mean)/(max - min)
df

,# Logins,# Content Reads,# Forum Reads,# Forum Posts,# Quiz Reviews before submission,Assignment 1 lateness indicator,Assignment 2 lateness indicator,Assignment 3 lateness indicator,Assignment 1 duration to submit (in hours),Assignment 2 duration to submit (in hours),Assignment 3 duration to submit (in hours),Average time to submit assignment (in hours),Engagement Level
0,0.097532,0.074159,1.000000,0.0,0.250000,0.0,0.0,0.0,-0.097597,-0.152386,-0.085367,-0.106060,0
1,-0.015297,0.072103,0.000000,0.0,0.333333,0.0,0.0,0.0,0.130885,0.203989,0.080271,0.126919,1
2,-0.058574,-0.054310,0.000000,0.0,0.250000,0.0,0.0,0.0,-0.114489,0.340690,0.149706,0.096273,1
3,0.018706,-0.000867,0.034483,0.0,0.500000,0.0,0.0,0.0,0.223796,0.375741,0.167452,0.236141,1
4,0.055800,0.110130,0.000000,0.0,0.083333,0.0,0.0,0.0,0.192935,0.342586,0.150359,0.210179,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,0.027980,0.009410,0.000000,0.0,0.083333,0.0,0.0,0.0,-0.103447,-0.161867,-0.096618,-0.115223,0
482,0.007887,-0.014228,0.017241,0.0,0.166667,0.0,0.0,0.0,-0.197245,-0.269378,-0.143443,-0.193266,0
483,0.029525,-0.067671,0.000000,0.0,0.500000,0.0,0.0,0.0,-0.098221,0.167156,0.084293,0.036579,1
484,-0.044663,-0.117003,0.000000,0.0,0.166667,0.0,0.0,0.0,-0.200663,-0.360167,-0.202279,-0.239852,0
485,0.014069,0.017632,0.000000,0.0,0.000000,0.0,0.0,0.0,0.168647,0.268403,0.108996,0.167187,1

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = df.iloc[:,0:11]
y = df.iloc[:,12]

# split the train and test dataset
X_train, X_test,y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=23)

# LogisticRegression
clf = LogisticRegression(random_state=0)
clf.fit(X_train, y_train)

# Prediction
y_pred = clf.predict(X_test)

acc = accuracy_score(y_test, y_pred)
print("Logistic Regression model accuracy (in %):", acc*100)

Logistic Regression model accuracy (in %): 100.0