In [1]:
path = "chromedriver"
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [2]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, TimeoutException

# Configuration
base_url = "https://www.topuniversities.com/world-university-rankings"

# Initialize WebDriver
options = webdriver.ChromeOptions()
# options.headless = True  # Uncomment if you do not need a browser UI.
driver = webdriver.Chrome(options=options)
driver.maximize_window()

# Initialize an empty list to store the data
data_list = []

def get_university_data(driver, url):
    try:
        driver.get(url)
        WebDriverWait(driver, 20).until(EC.visibility_of_element_located((By.CSS_SELECTOR, ".circle .score")))

        data = {}
        metrics = [
            "sustainability", "employment_outcomes", "international_research_network",
            "international_students_ratio", "international_faculty_ratio", "citations_per_faculty",
            "faculty_student_ratio", "employer_reputation", "academic_reputation", "overall"
        ]

        # Extract data from the circles on the page
        circles = driver.find_elements(By.CSS_SELECTOR, ".circle .score")
        for i, metric in enumerate(metrics):
            data[metric] = circles[i].text if i < len(circles) else None

        # Additional details
        data["QS_24"] = driver.find_element(By.CSS_SELECTOR, "#wur-tab .latest_rank").text
        data["location"] = driver.find_element(By.CSS_SELECTOR, "#p2-campus-location .active").text
        data["name"] = driver.find_element(By.CSS_SELECTOR, "#p2-overview .univ-block-heading").text
        
        return data

    except (NoSuchElementException, TimeoutException) as e:
        print(f"Error fetching data for URL {url}: {e}")
        return None  # Return None or {}

# Scrape multiple pages
try:
    for page in range(0, 15):
        driver.get(f"{base_url}?page={page}")
        WebDriverWait(driver, 20).until(EC.visibility_of_element_located((By.CSS_SELECTOR, ".uni-link")))
        links = driver.find_elements(By.CSS_SELECTOR, 'a.uni-link')
        urls = [link.get_attribute('href') for link in links]

        for url in urls:
            university_data = get_university_data(driver, url)
            if university_data:
                data_list.append(university_data)  # Append the data to the list
finally:
    driver.quit()

# Convert the list of dictionaries to a Pandas DataFrame
df = pd.DataFrame(data_list)

# Display the DataFrame
print(df)

The chromedriver version (123.0.6312.122) detected in PATH at C:\Users\DRITI SINGHANIA\ML\QS\chromedriver.exe might not be compatible with the detected chrome version (124.0.6367.63); currently, chromedriver 124.0.6367.91 is recommended for chrome 124.*, so it is advised to delete the driver in PATH and retry

Error fetching data for URL https://www.topuniversities.com/universities/sorbonne-university: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#p2-campus-location .active"}
  (Session info: chrome=124.0.6367.63); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF7FDF67032+63090]
	(No symbol) [0x00007FF7FDED2C82]
	(No symbol) [0x00007FF7FDD6EC65]
	(No symbol) [0x00007FF7FDDB499D]
	(No symbol) [0x00007FF7FDDB4ADC]
	(No symbol) [0x00007FF7FDDF5B37]
	(No symbol) [0x00007FF7FDDD701F]
	(No symbol) [0x00007FF7FDDF3412]
	(No symbol) [0x00007FF7FDDD6D83]
	(No symbol) [0x00007FF7FDDA83A8]
	(No symbol) [0x00007FF7FDDA9441]
	GetHandleVerifier [0x00007FF7FE3625AD+4238317]
	GetHandleVerifier [0x00007FF7FE39F70D+4488525]
	GetHandleVerifier [0x00007FF7FE3979EF+4456495]
	GetHandleVerifier [0x00007FF7FE040576+953270]
	(No symbol) [0x00007FF7FDEDE54F]
	(No symbol) [0x00007FF7FDED9224]
	(No symbol) [0x00007FF7FDED935B]
	(No symbol) [0x00007FF7FDEC9B94]
	BaseThreadInitThunk [0x00007FFD32C6257D+29]
	RtlUserThreadStart [0x00007FFD3484AA48+40]

    sustainability employment_outcomes international_research_network  \
0              100                 100                            100
1             99.2                 100                            100
2             98.9                 100                            100
3             98.3                 100                            100
4             98.1                 100                            100
..             ...                 ...                            ...
219           42.7                29.4                           15.1
220           42.5                28.9                           13.9
221           42.5                37.9                           15.2
222           42.4                22.1                           18.4
223           42.1                41.5                             20

    international_students_ratio international_faculty_ratio  \
0                            100                         100
1                            100                        92.3
2                            100                        90.6
3                           98.3                         100
4                            100                        99.9
..                           ...                         ...
219                         36.6                        65.1
220                         27.6                        74.9
221                         96.1                        38.7
222                         97.9                        51.6
223                         46.4                         100

    citations_per_faculty faculty_student_ratio employer_reputation  \
0                     100                  88.2                94.3
1                     100                  95.8                99.9
2                    98.2                  98.2                 100
3                    84.6                  66.8                 100
4                    99.9                  51.2                95.8
..                    ...                   ...                 ...
219                  99.9                  56.6                  48
220                  78.3                  20.2                78.8
221                     7                  14.9                81.1
222                  71.4                  91.7                31.3
223                   4.8                   1.7                 4.4

    academic_reputation overall  QS_24  \
0                   100    95.2     #1
1                   100    97.3     #2
2                   100    97.8     #3
3                   100    96.7     #4
4                   100    94.4     #5
..                  ...     ...    ...
219                27.9    61.6  #=220
220                15.7    82.7  #=222
221                33.1    90.5  #=222
222                26.6    33.2   #224
223                13.8    10.7   #225

                                              location name
0    Massachusetts Institute of Technology (MIT), M...
1              University of Cambridge, United Kingdom
2        Wellington Square, Oxford, GB, United Kingdom
3        Harvard College, Massachusetts, United States
4       Stanford University, California, United States
..                                                 ...  ...
219                        Dorigny Campus, Switzerland
220                      Campus Heyendaal, Netherlands
221           Pitt Campus, Pennsylvania, United States
222              River Campus, New York, United States
223                Bengaluru (Bangalore) Campus, India

[224 rows x 13 columns]

In [3]:
df.head(5)

,sustainability,employment_outcomes,international_research_network,international_students_ratio,international_faculty_ratio,citations_per_faculty,faculty_student_ratio,employer_reputation,academic_reputation,overall,QS_24,location,name
0,100,100,100,100,100,100,88.2,94.3,100,95.2,#1,"Massachusetts Institute of Technology (MIT), M...",
1,99.2,100,100,100,92.3,100,95.8,99.9,100,97.3,#2,"University of Cambridge, United Kingdom",
2,98.9,100,100,100,90.6,98.2,98.2,100,100,97.8,#3,"Wellington Square, Oxford, GB, United Kingdom",
3,98.3,100,100,98.3,100,84.6,66.8,100,100,96.7,#4,"Harvard College, Massachusetts, United States",
4,98.1,100,100,100,99.9,99.9,51.2,95.8,100,94.4,#5,"Stanford University, California, United States",

In [4]:
link = []
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://www.topuniversities.com/world-university-rankings")
time.sleep(5)
base_url = "https://www.topuniversities.com/world-university-rankings"
for page in range(0, 15):
        driver.get(f"{base_url}?page={page}")
        WebDriverWait(driver, 10).until(EC.visibility_of_element_located((By.ID, "ranking-data-load")))
        links = driver.find_elements(By.CSS_SELECTOR, 'a.uni-link')
        for i in links:
            i = i.text
            link.append(i)

The chromedriver version (123.0.6312.122) detected in PATH at C:\Users\DRITI SINGHANIA\ML\QS\chromedriver.exe might not be compatible with the detected chrome version (124.0.6367.63); currently, chromedriver 124.0.6367.91 is recommended for chrome 124.*, so it is advised to delete the driver in PATH and retry

In [5]:
print(link)

['Massachusetts Institute of Technology (MIT)', 'University of Cambridge', 'University of Oxford', 'Harvard University', 'Stanford University', 'Imperial College London', 'ETH Zurich', 'National University of Singapore (NUS)', 'UCL', 'University of California, Berkeley (UCB)', 'University of Chicago', 'University of Pennsylvania', 'Cornell University', 'The University of Melbourne', 'California Institute of Technology (Caltech)', 'Yale University', 'Peking University', 'Princeton University', 'The University of New South Wales (UNSW Sydney)', 'The University of Sydney', 'University of Toronto', 'The University of Edinburgh', 'Columbia University', 'Université PSL', 'Tsinghua University', 'Nanyang Technological University, Singapore (NTU Singapore)', 'The University of Hong Kong', 'Johns Hopkins University', 'The University of Tokyo', 'University of California, Los Angeles (UCLA)', 'McGill University', 'The University of Manchester', 'University of Michigan-Ann Arbor', 'Australian National University (ANU)', 'University of British Columbia', 'EPFL – École polytechnique fédérale de Lausanne', 'Technical University of Munich', 'Institut Polytechnique de Paris', 'New York University (NYU)', "King's College London", 'Seoul National University', 'Monash University', 'The University of Queensland', 'Zhejiang University', 'The London School of Economics and Political Science (LSE)', 'Kyoto University', 'Delft University of Technology', 'Northwestern University', 'The Chinese University of Hong Kong (CUHK)', 'Fudan University', 'Shanghai Jiao Tong University', 'Carnegie Mellon University', 'University of Amsterdam', 'Ludwig-Maximilians-Universität München', 'University of Bristol', 'KAIST - Korea Advanced Institute of Science & Technology', 'Duke University', 'University of Texas at Austin', 'Sorbonne University', 'The Hong Kong University of Science and Technology', 'KU Leuven', 'University of California, San Diego (UCSD)', 'University of Washington', 'University of Illinois at Urbana-Champaign', 'The Hong Kong Polytechnic University', 'Universiti Malaya (UM)', 'The University of Warwick', 'The University of Auckland', 'National Taiwan University (NTU)', 'City University of Hong Kong', 'Université Paris-Saclay', 'The University of Western Australia', 'Brown University', 'KTH Royal Institute of Technology', 'University of Leeds', 'Tokyo Institute of Technology (Tokyo Tech)', 'University of Zurich', 'Boston University', 'Universidad Nacional Autónoma de México (UNAM)', 'Universidad de Buenos Aires (UBA)', 'University of St Andrews', 'Georgia Institute of Technology', 'Freie Universitaet Berlin', 'Purdue University', 'Pohang University of Science And Technology (POSTECH)', 'University of Nottingham', 'University of Wisconsin-Madison', 'Pontificia Universidad Católica de Chile (UC)', 'The University of Sheffield', 'Uppsala University', 'RWTH Aachen University', 'University of Copenhagen', 'Utrecht University', 'Aalto University', 'Newcastle University', 'University of Alberta', 'University of Waterloo', 'Tohoku University', 'Western University', 'University of Helsinki', 'University of Southern California', 'University of Oslo', 'Stockholm University', 'University of California, Davis', 'KIT, Karlsruhe Institute of Technology', 'Humboldt-Universität zu Berlin', 'Technical University of Denmark', 'Lancaster University', 'Politecnico di Milano', 'Eindhoven University of Technology', 'University of Basel', 'Leiden University', 'University of Bern', 'University of Geneva', 'Chalmers University of Technology', 'Macquarie University (Sydney, Australia)', 'University of Vienna', 'University of North Carolina at Chapel Hill', 'Sapienza University of Rome', 'Texas A&M University', 'Michigan State University', 'Universiti Sains Malaysia (USM)', 'University of Science and Technology of China', 'University of Groningen', 'RMIT University', 'Nanjing University', 'Université de Montréal', 'Aarhus University', 'King Abdulaziz University (KAU)', 'Queen Mary University of London', 'Rice University', 'Sungkyunkwan University (SKKU)', 'University of Bath', 'Indian Institute of Technology Bombay (IITB)', 'Universitat Autònoma de Barcelona', 'The Ohio State University', 'Wageningen University & Research', 'University of Exeter', 'Alma Mater Studiorum - Università di Bologna', 'Cardiff University', 'Technische Universität Berlin (TU Berlin)', 'Washington University in St. Louis', 'Universiti Putra Malaysia (UPM)', 'Ghent University', 'Universidad de Chile', 'Universiti Kebangsaan Malaysia (UKM)', 'University of Wollongong', 'University of California, Santa Barbara (UCSB)', 'Hanyang University', 'Kyushu University', 'Universitat de Barcelona', 'Emory University', 'University of York', 'University of Florida', 'University of Maryland, College Park', 'University of Reading', 'Complutense University of Madrid', 'University College Dublin', 'Qatar University', 'The University of Newcastle, Australia (UON)', 'University of Cape Town', 'Erasmus University Rotterdam', 'Nagoya University', 'University of Liverpool', 'Arizona State University', 'KFUPM', 'Université catholique de Louvain (UCLouvain)', 'University of Calgary', 'Curtin University', 'Technische Universität Wien', 'Tecnológico de Monterrey', 'École Normale Supérieure de Lyon', 'University of Gothenburg', 'Universiti Teknologi Malaysia', 'McMaster University', 'Queensland University of Technology (QUT)', 'Universite libre de Bruxelles', 'Albert-Ludwigs-Universitaet Freiburg', 'Ecole des Ponts ParisTech', 'Wuhan University', 'University of Minnesota Twin Cities', 'Hokkaido University', 'Indian Institute of Technology Delhi (IITD)', 'Universidad de los Andes', 'Universidad Autónoma de Madrid', 'Waseda University', "Queen's University Belfast", 'King Saud University', 'University of Ottawa', 'Universität Hamburg', 'University of Otago', 'Vrije Universiteit Amsterdam', 'University of Aberdeen', "Queen's University at Kingston", 'University of Twente', 'Chulalongkorn University', 'Loughborough University', 'Eberhard Karls Universität Tübingen', 'Keio University', 'Tel Aviv University', 'Tongji University', 'National Yang Ming Chiao Tung University', 'University of Sussex', 'Università di Padova', 'Universidade Estadual de Campinas (Unicamp)', 'University of Lausanne', 'Radboud University', 'University of Pittsburgh', 'University of Rochester', 'Indian Institute of Science']

In [9]:
df.to_csv('QS.csv')